---
title: "owner-analysis"
format: html
author: "Kim Ely"
---

## Exercise: Explore, Clean, and Wrangle Data
Load libraries
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

Read in data
```{r}
lobster_abundance <- read_csv("../data/Lobster_Abundance_All_Years_20220829.csv")
```

Explore data
```{r}
## Check out column names
colnames(lobster_abundance)

## Peak at each column and class
glimpse(lobster_abundance)

## From when to when
range(lobster_abundance$DATE)

## Which sites?
unique(lobster_abundance$SITE)

```

## Cleaning data
Substitute NA for -9999 
```{r}
lobster_abundance <- lobster_abundance %>% 
  mutate(SIZE_MM = na_if(SIZE_MM, -99999))

unique(lobster_abundance$SIZE_MM)

```

Filter to exclude Naples Reef
```{r}
no_napl <- lobster_abundance %>% 
  filter(SITE != "NAPL")
unique(no_napl$SITE)
```

Filter to subset SITE == AQUE and length > 70 mm
```{r}
aque_70 <- lobster_abundance %>% 
  filter(SITE == "AQUE", SIZE_MM >= 70)
summary(aque_70)
```

## Exercise: Data Visualization
```{r}
ggplot(lobster_abundance, 
       aes(x = SIZE_MM)) +
  geom_histogram() +
  facet_wrap(~SITE)+
  labs(title = "Lobster Size by Region")+
  theme_bw()
ggsave("figs/lobster_size_region.jpg", width = 8, height = 6, units = "in")
```

